let playing = false;
let score;
let scoreText;
let roundText;
let warningText;
let PDrops;
let emitter;
let gameLost;
let gameWon;
let crosshairs;
const MAX_PDROPS = 1000;
let round = 0;
let pint = [];
let started = false;
let start;
let pSource;
let count = 0;
let target;
let pee;
const PEE_LIFESPAN = 750;
const NUM_ROUNDS = 8;
let warninglife = 100;
let warnings = 1;
let soundButton;
let soundOn = true;
let blurinal;
let startGame = false;
let startButton;
let localStorage;
const localStorageName = 'aimGame';
var highScoreText;
var highScore = 0;
//SOUNDS
var boo;
var cheer;
var flush
var music1;
var music2;
var peeMetal;
var peeSplash1;
var peeSplash2;
var peeWater;
var relief1;
var relief2;
var relief3;
var relief4;
var shoes1;
var shoes2;
var zip;
var streams = [];
var title;
var miss;
var splash;
var relief;